package epmc.imdp.options;

/**
 * Class collecting options used for IMDP plugin.
 * 
 * @author Ernst Moritz Hahn
 */
public enum OptionsIMDPLump {
	/** Base name of resource file for options description. */
	OPTIONS_IMDP_LUMP,
	IMDP_LUMP_CATEGORY,
	IMDP_LUMP_METHOD,
	IMDP_SHORTCUT_ZERO_ACTIONS,
	IMDP_SHORTCUT_SINGLE_ACTION_BEFORE_NORMALISATION,
	IMDP_SHORTCUT_UNSIMULABLE_BLOCK,
	IMDP_SHORTCUT_SINGLE_ACTION_AFTER_NORMALISATION,
	IMDP_PROBLEM_SET_CACHE_BEFORE_NORMALISATION,
	IMDP_PROBLEM_SET_CACHE_AFTER_NORMALISATION,
	IMDP_LP_CACHE_TYPE,
	IMDP_OUTPUT_TYPE,
	IMDP_NO_SELF_COMPARE,
	IMDP_SPLIT_BLOCK_METHOD,
	IMDP_SIGNATURE_NORMALISE,
	;
}
