package epmc.dd.cuddmtbdd;

// TODO complete documentation

public enum OptionsDDCUDDMTBDD {
    OPTIONS_DD_CUDD_MTBDD,
    DD_CUDD_MTBDD_CATEGORY,
    DD_CUDD_MTBDD_INIT_CACHE_SIZE,
    DD_CUDD_MTBDD_MAX_MEMORY,
    DD_CUDD_MTBDD_UNIQUE_SLOTS,
    DD_CUDD_MTBDD_MAX_CACHE_HARD,
    DD_CUDD_MTBDD_MIN_HIT,
    DD_CUDD_MTBDD_GARBAGE_COLLECT,
    DD_CUDD_MTBDD_LOOSE_UP_TO,
}
