/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package epmc.prism.model;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 5;
  /** RegularExpression Id. */
  int BOOL = 6;
  /** RegularExpression Id. */
  int CEIL = 7;
  /** RegularExpression Id. */
  int CLOCK = 8;
  /** RegularExpression Id. */
  int CONSTANT = 9;
  /** RegularExpression Id. */
  int CTMC = 10;
  /** RegularExpression Id. */
  int CTMDP = 11;
  /** RegularExpression Id. */
  int C = 12;
  /** RegularExpression Id. */
  int DOUBLE = 13;
  /** RegularExpression Id. */
  int DTMC = 14;
  /** RegularExpression Id. */
  int E = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int FORMULA = 17;
  /** RegularExpression Id. */
  int FILTER = 18;
  /** RegularExpression Id. */
  int FLOOR = 19;
  /** RegularExpression Id. */
  int FUNCTION = 20;
  /** RegularExpression Id. */
  int F = 21;
  /** RegularExpression Id. */
  int GLOBAL = 22;
  /** RegularExpression Id. */
  int G = 23;
  /** RegularExpression Id. */
  int INIT = 24;
  /** RegularExpression Id. */
  int INVARIANT_OPEN = 25;
  /** RegularExpression Id. */
  int I = 26;
  /** RegularExpression Id. */
  int IMC = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int LABEL = 29;
  /** RegularExpression Id. */
  int LOG = 30;
  /** RegularExpression Id. */
  int MA = 31;
  /** RegularExpression Id. */
  int MAX = 32;
  /** RegularExpression Id. */
  int MDP = 33;
  /** RegularExpression Id. */
  int MIN = 34;
  /** RegularExpression Id. */
  int MOD = 35;
  /** RegularExpression Id. */
  int MODULEBEGIN = 36;
  /** RegularExpression Id. */
  int MODULEEND = 37;
  /** RegularExpression Id. */
  int MULTIOBJECTIVE = 38;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 39;
  /** RegularExpression Id. */
  int P = 40;
  /** RegularExpression Id. */
  int PMAX = 41;
  /** RegularExpression Id. */
  int PMIN = 42;
  /** RegularExpression Id. */
  int POW = 43;
  /** RegularExpression Id. */
  int PROBABILISTIC = 44;
  /** RegularExpression Id. */
  int PROB = 45;
  /** RegularExpression Id. */
  int PTA = 46;
  /** RegularExpression Id. */
  int R = 47;
  /** RegularExpression Id. */
  int RATE = 48;
  /** RegularExpression Id. */
  int REWARDSBEGIN = 49;
  /** RegularExpression Id. */
  int REWARDSEND = 50;
  /** RegularExpression Id. */
  int RMAX = 51;
  /** RegularExpression Id. */
  int RMIN = 52;
  /** RegularExpression Id. */
  int S = 53;
  /** RegularExpression Id. */
  int SMAX = 54;
  /** RegularExpression Id. */
  int SMIN = 55;
  /** RegularExpression Id. */
  int SQRT = 56;
  /** RegularExpression Id. */
  int STOCHASTIC = 57;
  /** RegularExpression Id. */
  int SYSTEMBEGIN = 58;
  /** RegularExpression Id. */
  int SYSTEMEND = 59;
  /** RegularExpression Id. */
  int TRUE = 60;
  /** RegularExpression Id. */
  int U = 61;
  /** RegularExpression Id. */
  int W = 62;
  /** RegularExpression Id. */
  int X = 63;
  /** RegularExpression Id. */
  int COND = 64;
  /** RegularExpression Id. */
  int PLUS = 65;
  /** RegularExpression Id. */
  int MINUS = 66;
  /** RegularExpression Id. */
  int TIMES = 67;
  /** RegularExpression Id. */
  int DIVIDE = 68;
  /** RegularExpression Id. */
  int LBRACKET = 69;
  /** RegularExpression Id. */
  int RBRACKET = 70;
  /** RegularExpression Id. */
  int LPAR = 71;
  /** RegularExpression Id. */
  int RPAR = 72;
  /** RegularExpression Id. */
  int LCURL = 73;
  /** RegularExpression Id. */
  int RCURL = 74;
  /** RegularExpression Id. */
  int RENAME = 75;
  /** RegularExpression Id. */
  int SEMICOLON = 76;
  /** RegularExpression Id. */
  int COLON = 77;
  /** RegularExpression Id. */
  int COMMA = 78;
  /** RegularExpression Id. */
  int AND = 79;
  /** RegularExpression Id. */
  int OR = 80;
  /** RegularExpression Id. */
  int NOT = 81;
  /** RegularExpression Id. */
  int IMPLIES = 82;
  /** RegularExpression Id. */
  int IFF = 83;
  /** RegularExpression Id. */
  int QUESTION = 84;
  /** RegularExpression Id. */
  int PRIME = 85;
  /** RegularExpression Id. */
  int EQ = 86;
  /** RegularExpression Id. */
  int NEQ = 87;
  /** RegularExpression Id. */
  int LEQ = 88;
  /** RegularExpression Id. */
  int LT = 89;
  /** RegularExpression Id. */
  int GT = 90;
  /** RegularExpression Id. */
  int GEQ = 91;
  /** RegularExpression Id. */
  int QUOTE = 92;
  /** RegularExpression Id. */
  int SMG = 93;
  /** RegularExpression Id. */
  int COALITION_OPEN = 94;
  /** RegularExpression Id. */
  int COALITION_CLOSE = 95;
  /** RegularExpression Id. */
  int PLAYERBEGIN = 96;
  /** RegularExpression Id. */
  int PLAYEREND = 97;
  /** RegularExpression Id. */
  int IDENTIFIER = 98;
  /** RegularExpression Id. */
  int NUM_INT = 99;
  /** RegularExpression Id. */
  int NUM_REAL = 100;
  /** RegularExpression Id. */
  int ARROW_ARROW = 101;
  /** RegularExpression Id. */
  int ARROW_ARG = 102;
  /** RegularExpression Id. */
  int SEPINTERVAL_SEPINTERVAL = 103;
  /** RegularExpression Id. */
  int SEPINTERVAL_ARG = 104;
  /** RegularExpression Id. */
  int INVARIANT_CLOSE = 105;
  /** RegularExpression Id. */
  int INVARIANT_IDENTIFIER = 106;
  /** RegularExpression Id. */
  int INVARIANT_OTHER = 107;
  /** RegularExpression Id. */
  int INIT_CLOSE = 108;
  /** RegularExpression Id. */
  int INIT_IDENTIFIER = 109;
  /** RegularExpression Id. */
  int INIT_OTHER = 110;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_SEMICOLON = 111;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_OTHER = 112;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_BRACKET_OPEN = 113;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_INNER_OTHER = 114;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_INNER_BRACKET_OPEN = 115;
  /** RegularExpression Id. */
  int NESTING_SEMICOLON_INNER_BRACKET_CLOSE = 116;
  /** RegularExpression Id. */
  int NESTING_BRACKET_RBRACKET = 117;
  /** RegularExpression Id. */
  int NESTING_BRACKET_OTHER = 118;
  /** RegularExpression Id. */
  int NESTING_BRACKET_BRACKET_OPEN = 119;
  /** RegularExpression Id. */
  int NESTING_BRACKET_INNER_OTHER = 120;
  /** RegularExpression Id. */
  int NESTING_BRACKET_INNER_BRACKET_OPEN = 121;
  /** RegularExpression Id. */
  int NESTING_BRACKET_INNER_BRACKET_CLOSE = 122;
  /** RegularExpression Id. */
  int NESTING_PAR_RPAR = 123;
  /** RegularExpression Id. */
  int NESTING_PAR_OTHER = 124;
  /** RegularExpression Id. */
  int NESTING_PAR_PAR_OPEN = 125;
  /** RegularExpression Id. */
  int UPDATE_TRUE = 126;
  /** RegularExpression Id. */
  int UPDATE_LPAR = 127;
  /** RegularExpression Id. */
  int UPDATE_SEMICOLON = 128;
  /** RegularExpression Id. */
  int UPDATE_PRIME = 129;
  /** RegularExpression Id. */
  int UPDATE_EQ = 130;
  /** RegularExpression Id. */
  int UPDATE_PLUS = 131;
  /** RegularExpression Id. */
  int UPDATE_AND = 132;
  /** RegularExpression Id. */
  int UPDATE_IDENTIFIER = 133;
  /** RegularExpression Id. */
  int UPDATE_OTHER = 134;
  /** RegularExpression Id. */
  int NESTING_PAR_INNER_OTHER = 135;
  /** RegularExpression Id. */
  int NESTING_PAR_INNER_PAR_OPEN = 136;
  /** RegularExpression Id. */
  int NESTING_PAR_INNER_PAR_CLOSE = 137;
  /** RegularExpression Id. */
  int NESTING_COLON_COLON = 138;
  /** RegularExpression Id. */
  int NESTING_COLON_OTHER = 139;
  /** RegularExpression Id. */
  int NESTING_COLON_QUESTION = 140;
  /** RegularExpression Id. */
  int NESTING_COLON_INNER_OTHER = 141;
  /** RegularExpression Id. */
  int NESTING_COLON_INNER_QUESTION = 142;
  /** RegularExpression Id. */
  int NESTING_COLON_INNER_COLON = 143;
  /** RegularExpression Id. */
  int COMMENT = 144;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 145;

  /** Lexical state. */
  int NESTING_COLON_INNER = 0;
  /** Lexical state. */
  int NESTING_COLON = 1;
  /** Lexical state. */
  int NESTING_PAR_INNER = 2;
  /** Lexical state. */
  int UPDATE_ENV = 3;
  /** Lexical state. */
  int NESTING_PAR = 4;
  /** Lexical state. */
  int NESTING_BRACKET_INNER = 5;
  /** Lexical state. */
  int NESTING_BRACKET = 6;
  /** Lexical state. */
  int NESTING_SEMICOLON_INNER = 7;
  /** Lexical state. */
  int NESTING_SEMICOLON = 8;
  /** Lexical state. */
  int INIT_ENV = 9;
  /** Lexical state. */
  int INVARIANT_ENV = 10;
  /** Lexical state. */
  int SEPINTERVAL_ENV = 11;
  /** Lexical state. */
  int ARROW_ENV = 12;
  /** Lexical state. */
  int DEFAULT = 13;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"A\"",
    "\"bool\"",
    "\"ceil\"",
    "\"clock\"",
    "\"const\"",
    "\"ctmc\"",
    "\"ctmdp\"",
    "\"C\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"floor\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"invariant\"",
    "\"I\"",
    "\"imc\"",
    "\"int\"",
    "\"label\"",
    "\"log\"",
    "\"ma\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"mod\"",
    "\"module\"",
    "\"endmodule\"",
    "\"multi\"",
    "\"nondeterministic\"",
    "\"P\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"pow\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"R\"",
    "\"rate\"",
    "\"rewards\"",
    "\"endrewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"S\"",
    "\"Smax\"",
    "\"Smin\"",
    "\"sqrt\"",
    "\"stochastic\"",
    "\"system\"",
    "\"endsystem\"",
    "\"true\"",
    "\"U\"",
    "\"W\"",
    "\"X\"",
    "\"given\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"<-\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=>\"",
    "\"<=>\"",
    "\"?\"",
    "\"\\\'\"",
    "\"=\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"\\\"\"",
    "\"smg\"",
    "\"<<\"",
    "\">>\"",
    "\"player\"",
    "\"endplayer\"",
    "<IDENTIFIER>",
    "<NUM_INT>",
    "<NUM_REAL>",
    "\"->\"",
    "<ARROW_ARG>",
    "\"..\"",
    "<SEPINTERVAL_ARG>",
    "\"endinvariant\"",
    "<INVARIANT_IDENTIFIER>",
    "<INVARIANT_OTHER>",
    "\"endinit\"",
    "<INIT_IDENTIFIER>",
    "<INIT_OTHER>",
    "\";\"",
    "<NESTING_SEMICOLON_OTHER>",
    "\"[\"",
    "<NESTING_SEMICOLON_INNER_OTHER>",
    "\"[\"",
    "\"]\"",
    "\"]\"",
    "<NESTING_BRACKET_OTHER>",
    "\"[\"",
    "<NESTING_BRACKET_INNER_OTHER>",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "<NESTING_PAR_OTHER>",
    "\"(\"",
    "\"true\"",
    "\"(\"",
    "\";\"",
    "\"\\\'\"",
    "\"=\"",
    "\"+\"",
    "\"&\"",
    "<UPDATE_IDENTIFIER>",
    "<UPDATE_OTHER>",
    "<NESTING_PAR_INNER_OTHER>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<NESTING_COLON_OTHER>",
    "\"?\"",
    "<NESTING_COLON_INNER_OTHER>",
    "\"?\"",
    "\":\"",
    "<COMMENT>",
    "<UNEXPECTED_CHAR>",
  };

}
