package epmc.webserver.backend.worker.task.worked.completed;

import java.util.List;

import epmc.webserver.common.Pair;
import epmc.webserver.common.TaskOperation;

/**
 * A task representing a completed model check task, i.e., a task requiring the check of a model that has been successfully finished
 * @author ori
 */
public class CompletedCheckModelTask extends CompletedTask {
	private final List<Pair<Integer, String>> results;
	
	/**
	 * Create a new completed task identified by taskId for the user identified by userId
	 * @param userId the identifier of the user this task belongs to, as in the database
	 * @param taskId the identifier of this task, as in the database
	 * @param operation the operation to perform on this task, as extracted from the database
	 * @param results the results of the task
	 */
	public CompletedCheckModelTask(int userId, int taskId, TaskOperation operation, List<Pair<Integer, String>> results) {
		super(userId, taskId, operation);
		this.results = results;
	}
	
	/**
	 * Return the list of results generated by the model checker.
	 * Each pair contains the formula identifier (from the database) and the relative result
	 * @return the list of results
	 */
	public List<Pair<Integer, String>> getResults() {
		return results;
	}
}
