package epmc.dd.cudd;

public enum OptionsDDCUDD {
    OPTIONS_DD_CUDD,
    DD_CUDD_CATEGORY,
    DD_CUDD_SUBENGINE,
    DD_CUDD_INIT_CACHE_SIZE,
    DD_CUDD_MAX_MEMORY,
    DD_CUDD_UNIQUE_SLOTS,
    DD_CUDD_MAX_CACHE_HARD,
    DD_CUDD_MIN_HIT,
    DD_CUDD_GARBAGE_COLLECT,
    DD_CUDD_LOOSE_UP_TO,
    DD_CUDD_REORDER_HEURISTIC,
}
