package epmc.dd.sylvan;

public enum OptionsDDSylvan {
    OPTIONS_DD_SYLVAN,
    DD_SYLVAN_CATEGORY,
    DD_SYLVAN_INIT_CACHE_SIZE,
    DD_SYLVAN_INIT_NODES,
    DD_SYLVAN_WORKERS,
    DD_SYLVAN_CACHE_GRANULARITY,
}
