package epmc.dd.sylvanmtbdd;

public enum OptionsDDSylvanMTBDD {
    OPTIONS_DD_SYLVAN_MTBDD,
    DD_SYLVAN_MTBDD_CATEGORY,
    DD_SYLVAN_MTBDD_INIT_CACHE_SIZE,
    DD_SYLVAN_MTBDD_INIT_NODES,
    DD_SYLVAN_MTBDD_WORKERS,
    DD_SYLVAN_MTBDD_CACHE_GRANULARITY,
}
