/* Generated By:JavaCC: Do not edit this line. GuardedCommandExpressionParser.java */
package epmc.guardedcommand.expression;
import epmc.error.UtilError;
import epmc.guardedcommand.error.ProblemsGuardedCommand;
import epmc.error.Positional;
import static epmc.error.UtilError.ensure;
import epmc.error.EPMCException;
import epmc.value.Operator;
import epmc.value.Value;
import epmc.value.ContextValue;
import epmc.value.OperatorAnd;
import epmc.value.OperatorNot;
import epmc.value.OperatorAddInverse;
import epmc.value.OperatorImplies;
import epmc.value.OperatorIff;
import epmc.value.OperatorOr;
import epmc.value.OperatorIte;
import epmc.value.OperatorEq;
import epmc.value.OperatorNe;
import epmc.value.OperatorAdd;
import epmc.value.OperatorSubtract;
import epmc.value.OperatorLe;
import epmc.value.OperatorLt;
import epmc.value.OperatorGe;
import epmc.value.OperatorGt;
import epmc.value.OperatorMultiply;
import epmc.value.OperatorDivide;
import epmc.value.OperatorPow;
import epmc.value.OperatorMax;
import epmc.value.OperatorMin;
import epmc.value.OperatorCeil;
import epmc.value.OperatorFloor;
import epmc.value.OperatorLog;
import epmc.value.OperatorMod;
import epmc.value.ValueInteger;
import epmc.value.TypeInteger;
import epmc.value.TypeReal;
import epmc.value.UtilValue;
import epmc.value.ValueAlgebra;
import epmc.expression.*;
import epmc.expression.standard.ExpressionIdentifierStandard;
import epmc.expression.standard.ExpressionFilter;
import epmc.expression.standard.ExpressionMultiObjective;
import epmc.expression.standard.ExpressionCoalition;
import epmc.expression.standard.ExpressionTemporal;
import epmc.expression.standard.ExpressionReward;
import epmc.expression.standard.ExpressionQuantifier;
import epmc.expression.standard.ExpressionSteadyState;
import epmc.expression.standard.ExpressionLiteral;
import epmc.expression.standard.ExpressionOperator;
import epmc.expression.standard.TemporalType;
import epmc.expression.standard.FilterType;
import epmc.expression.standard.TimeBound;
import epmc.expression.standard.RewardType;
import epmc.expression.standard.CmpType;
import epmc.expression.standard.DirType;

import java.util.ArrayList;
import java.util.List;

public final class GuardedCommandExpressionParser implements GuardedCommandExpressionParserConstants {
        private ContextValue contextVal;
        private int initialLine;
        private int initialColumn;
        private int errorLine;
        private int errorColumn;

        private void computeErrorPosition(int tline, int tcolumn) {
                errorLine = tline + initialLine - 1;
                errorColumn = tcolumn;
                if (tline == 1) {
                        errorColumn += initialColumn - 1;
                }
        }

        public Expression parseExpression(ContextValue contextVal) throws EPMCException {
                return parseExpression(contextVal, 1, 1);
        }

        public Expression parseExpression(ContextValue contextVal, int line, int column) throws EPMCException {
                this.contextVal = contextVal;
                this.initialLine = line;
                this.initialColumn = column;

                try {
                        return parseCompleteExp();
                } catch (ParseException pe) {
                        Token errorToken = getToken(1);
                        if (errorToken.kind == UNEXPECTED_CHAR) {
                                computeErrorPosition(errorToken.endLine, errorToken.endColumn);
                                ensure(false, ProblemsGuardedCommand.GUARDEDCOMMAND_EXPRESSION_PARSER_UNEXPECTED_CHARACTER, newPositional(errorLine, errorColumn), errorToken.image);
                        } else {
                                computeErrorPosition(errorToken.beginLine, errorToken.beginColumn);
                                ensure(false, ProblemsGuardedCommand.GUARDEDCOMMAND_EXPRESSION_PARSER_SYNTAX_ERROR, newPositional(errorLine, errorColumn), errorToken.toString());
                        }
                        return null;
        } catch (EPMCException e) {
                   throw e;
                }
                catch (Throwable t) {
                  ensure(false, ProblemsGuardedCommand.GUARDEDCOMMAND_EXPRESSION_PARSER_GENERAL_ERROR, t, t);
                  return null;
                }
        }

        private ExpressionOperator newOperator(Operator operator, Expression... operands) {
          return new ExpressionOperator.Builder()
                .setOperator(operator)
                .setOperands(operands)
                .build();
        }

        private ExpressionOperator newOperator(String operator, Expression... operands) {
          return new ExpressionOperator.Builder()
                .setOperator(contextVal.getOperator(operator))
                .setOperands(operands)
                .build();
        }

  private Expression and(Expression a, Expression b) {
      return newOperator(OperatorAnd.IDENTIFIER, a, b);
  }

    private Expression not(Expression expression) {
        return new ExpressionOperator.Builder()
                .setOperator(contextVal.getOperator(OperatorNot.IDENTIFIER))
                .setOperands(expression)
                .build();
    }

  private Expression addInverse(Expression expression) {
    return new ExpressionOperator.Builder()
        .setOperator(contextVal.getOperator(OperatorAddInverse.IDENTIFIER))
        .setOperands(expression)
        .build();
  }

    private Expression or(Expression a, Expression b) {
        return new ExpressionOperator.Builder()
            .setOperator(contextVal.getOperator(OperatorOr.IDENTIFIER))
            .setOperands(a, b)
            .build();
    }

    private Expression iff(Expression a, Expression b) {
        return new ExpressionOperator.Builder()
            .setOperator(contextVal.getOperator(OperatorIff.IDENTIFIER))
            .setOperands(a, b)
            .build();
    }

    private Expression implies(Expression a, Expression b) {
        return new ExpressionOperator.Builder()
            .setOperator(contextVal.getOperator(OperatorImplies.IDENTIFIER))
            .setOperands(a, b)
            .build();
    }

    private static boolean isPosInf(Expression expression) {
        assert expression != null;
        if (!(expression instanceof ExpressionLiteral)) {
            return false;
        }
        ExpressionLiteral expressionLiteral = (ExpressionLiteral) expression;
        return ValueAlgebra.asAlgebra(expressionLiteral.getValue()).isPosInf();
    }

    private ValueInteger newValueInteger(String string) throws EPMCException {
      assert string != null;
      return UtilValue.newValue(TypeInteger.get(contextVal), string);
  }

    private static Positional newPositional(long line, long column) {
        assert line >= 0;
        assert column >= 0;
        return new Positional.Builder()
                .setLine(line)
                .setColumn(column)
                .build();
    }

  final private Expression parseCompleteExp() throws ParseException, EPMCException {
        Expression e;
    e = parseExp();
    jj_consume_token(0);
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseExp() throws ParseException, EPMCException {
        Expression e;
    e = ExpressionITE();
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionITE() throws ParseException, EPMCException {
        Expression prop;
        Expression propThen;
        Expression propElse;
    prop = ExpressionImplies();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUESTION:
      jj_consume_token(QUESTION);
      propThen = ExpressionImplies();
      jj_consume_token(COLON);
      propElse = ExpressionITE();
                  prop = new ExpressionOperator.Builder()
                        .setOperator(contextVal.getOperator(OperatorIte.IDENTIFIER))
                        .setOperands(prop, propThen, propElse)
                        .build();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
          {if (true) return prop;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionImplies() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
    p = ExpressionIff();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPLIES:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(IMPLIES);
      nextProp = ExpressionIff();
                  p = implies(p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionIff() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
    p = ExpressionOr();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IFF:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      jj_consume_token(IFF);
      nextProp = ExpressionOr();
                  p = iff(p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionOr() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
    p = ExpressionAnd();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      jj_consume_token(OR);
      nextProp = ExpressionAnd();
                  p = or(p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionAnd() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
    p = ExpressionNot();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      jj_consume_token(AND);
      nextProp = ExpressionNot();
                  p = and(p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionNot() throws ParseException, EPMCException {
          Expression p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      p = ExpressionNot();
                  p = not(p);
      break;
    case CEIL:
    case FALSE:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case POW:
    case SQRT:
    case TRUE:
    case MINUS:
    case LPAR:
    case QUOTE:
    case IDENTIFIER:
    case NUM_INT:
    case NUM_REAL:
      p = ExpressionEqNe();
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionEqNe() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
        Operator type;
    p = ExpressionROp();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
      case NEQ:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      type = EqNe();
      nextProp = ExpressionROp();
                  p = newOperator(type, p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator EqNe() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
                  {if (true) return contextVal.getOperator(OperatorEq.IDENTIFIER);}
      break;
    case NEQ:
      jj_consume_token(NEQ);
                  {if (true) return contextVal.getOperator(OperatorNe.IDENTIFIER);}
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionROp() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
        Operator type;
    p = ExpressionPlusMinus();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEQ:
      case LT:
      case GT:
      case GEQ:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_6;
      }
      type = LtGtLeGe();
      nextProp = ExpressionPlusMinus();
                  p = newOperator(type, p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator LtGtLeGe() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      jj_consume_token(LT);
                  {if (true) return contextVal.getOperator(OperatorLt.IDENTIFIER);}
      break;
    case LEQ:
      jj_consume_token(LEQ);
                  {if (true) return contextVal.getOperator(OperatorLe.IDENTIFIER);}
      break;
    case GT:
      jj_consume_token(GT);
                  {if (true) return contextVal.getOperator(OperatorGt.IDENTIFIER);}
      break;
    case GEQ:
      jj_consume_token(GEQ);
                  {if (true) return contextVal.getOperator(OperatorGe.IDENTIFIER);}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionPlusMinus() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
        Operator type;
    p = ExpressionTimesDivide();
    label_7:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_7;
      }
      type = PlusMinus();
      nextProp = ExpressionTimesDivide();
                  p = newOperator(type, p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator PlusMinus() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      jj_consume_token(PLUS);
                  {if (true) return contextVal.getOperator(OperatorAdd.IDENTIFIER);}
      break;
    case MINUS:
      jj_consume_token(MINUS);
                  {if (true) return contextVal.getOperator(OperatorSubtract.IDENTIFIER);}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionTimesDivide() throws ParseException, EPMCException {
        Expression p;
        Expression nextProp;
        Operator type;
    p = ExpressionUnaryMinus();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      type = TimesDivide();
      nextProp = ExpressionUnaryMinus();
                  p = newOperator(type, p, nextProp);
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Operator TimesDivide() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIMES:
      jj_consume_token(TIMES);
                  {if (true) return contextVal.getOperator(OperatorMultiply.IDENTIFIER);}
      break;
    case DIVIDE:
      jj_consume_token(DIVIDE);
                  {if (true) return contextVal.getOperator(OperatorDivide.IDENTIFIER);}
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression ExpressionUnaryMinus() throws ParseException, EPMCException {
          Expression p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
      p = ExpressionUnaryMinus();
                  p = addInverse(p);
      break;
    case CEIL:
    case FALSE:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case POW:
    case SQRT:
    case TRUE:
    case LPAR:
    case QUOTE:
    case IDENTIFIER:
    case NUM_INT:
    case NUM_REAL:
      p = parseBasic();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseBasic() throws ParseException, EPMCException {
        Expression e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case TRUE:
      e = parseBoolean();
      break;
    case CEIL:
    case FLOOR:
    case FUNCTION:
    case LOG:
    case MAX:
    case MIN:
    case MOD:
    case POW:
    case SQRT:
      e = parseFunction();
      break;
    case IDENTIFIER:
      e = parseIdentifier();
      break;
    case NUM_INT:
      e = parseInt();
      break;
    case NUM_REAL:
      e = parseReal();
      break;
    case LPAR:
      e = parseParenth();
      break;
    case QUOTE:
      e = parseLabel();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction() throws ParseException, EPMCException {
        Expression e;
        Expression ne;
        Operator type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SQRT:
      e = parseSpecialFunction();
      break;
    case MAX:
    case MIN:
      type = functionMultipleParams();
      jj_consume_token(LPAR);
      e = parseFunctionN(type);
      jj_consume_token(RPAR);
      break;
    case LOG:
    case MOD:
    case POW:
      type = functionTwoParams();
      jj_consume_token(LPAR);
      e = parseFunction2(type);
      jj_consume_token(RPAR);
      break;
    case CEIL:
    case FLOOR:
      type = functionOneParam();
      jj_consume_token(LPAR);
      e = parseFunction1(type);
      jj_consume_token(RPAR);
      break;
    case FUNCTION:
      jj_consume_token(FUNCTION);
      jj_consume_token(LPAR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SQRT:
        e = parseSqrt();
        break;
      case MAX:
      case MIN:
        type = functionMultipleParams();
        jj_consume_token(COMMA);
        e = parseFunctionN(type);
        break;
      case LOG:
      case MOD:
      case POW:
        type = functionTwoParams();
        jj_consume_token(COMMA);
        e = parseFunction2(type);
        break;
      case CEIL:
      case FLOOR:
        type = functionOneParam();
        jj_consume_token(COMMA);
        e = parseFunction1(type);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(RPAR);
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseSpecialFunction() throws ParseException, EPMCException {
        Expression e;
    e = parseSqrt();
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseSqrt() throws ParseException, EPMCException {
        Expression e;
    jj_consume_token(SQRT);
    jj_consume_token(LPAR);
    e = parseExp();
    jj_consume_token(RPAR);
          {if (true) return newOperator(contextVal.getOperator(OperatorPow.IDENTIFIER), e,
                new ExpressionLiteral.Builder()
                        .setValue(UtilValue.newValue(TypeReal.get(contextVal), "0.5"))
                        .build());}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunctionN(Operator type) throws ParseException, EPMCException {
        Expression e;
        Expression ne;
    e = parseExp();
    label_9:
    while (true) {
      jj_consume_token(COMMA);
      ne = parseExp();
                  e = newOperator(type, e, ne);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_9;
      }
    }
          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction2(Operator type) throws ParseException, EPMCException {
        Expression e;
        Expression ne;
    e = parseExp();
    jj_consume_token(COMMA);
    ne = parseExp();
          {if (true) return newOperator(type, e, ne);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseFunction1(Operator type) throws ParseException, EPMCException {
        Expression e;
    e = parseExp();
          {if (true) return newOperator(type, e);}
    throw new Error("Missing return statement in function");
  }

  final private Operator functionMultipleParams() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAX:
      jj_consume_token(MAX);
                  {if (true) return contextVal.getOperator(OperatorMax.IDENTIFIER);}
      break;
    case MIN:
      jj_consume_token(MIN);
                  {if (true) return contextVal.getOperator(OperatorMin.IDENTIFIER);}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Operator functionOneParam() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FLOOR:
      jj_consume_token(FLOOR);
                  {if (true) return contextVal.getOperator(OperatorFloor.IDENTIFIER);}
      break;
    case CEIL:
      jj_consume_token(CEIL);
                  {if (true) return contextVal.getOperator(OperatorCeil.IDENTIFIER);}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Operator functionTwoParams() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POW:
      jj_consume_token(POW);
                  {if (true) return contextVal.getOperator(OperatorPow.IDENTIFIER);}
      break;
    case MOD:
      jj_consume_token(MOD);
                  {if (true) return contextVal.getOperator(OperatorMod.IDENTIFIER);}
      break;
    case LOG:
      jj_consume_token(LOG);
                  {if (true) return contextVal.getOperator(OperatorLog.IDENTIFIER);}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Expression parseParenth() throws ParseException, EPMCException {
        Expression p;
    jj_consume_token(LPAR);
    p = parseExp();
    jj_consume_token(RPAR);
          {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseIdentifier() throws ParseException, EPMCException {
        Token literal;
    literal = jj_consume_token(IDENTIFIER);
          {if (true) return new ExpressionIdentifierStandard.Builder()
                .setName(literal.toString())
                .build();}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseLabel() throws ParseException, EPMCException {
        Token literal;
    jj_consume_token(QUOTE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      literal = jj_consume_token(IDENTIFIER);
      break;
    case INIT:
      literal = jj_consume_token(INIT);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(QUOTE);
          {if (true) return new ExpressionIdentifierStandard.Builder()
                .setName("\u005c"" + literal.toString() + "\u005c"")
                .build();}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseReal() throws ParseException, EPMCException {
        Token real;
    real = jj_consume_token(NUM_REAL);
          {if (true) return new ExpressionLiteral.Builder()
                .setValue(UtilValue.newValue(TypeReal.get(contextVal), real.toString()))
                .build();}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseInt() throws ParseException, EPMCException {
        Token intg;
    intg = jj_consume_token(NUM_INT);
          {if (true) return new ExpressionLiteral.Builder()
                .setValue(newValueInteger(intg.toString()))
                .build();}
    throw new Error("Missing return statement in function");
  }

  final private List<Expression> parseList() throws ParseException, EPMCException {
        List<Expression> vector = new ArrayList<Expression>();
        Expression element;
    element = parseExp();
          vector.add(element);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMMA);
      element = parseExp();
                  vector.add(element);
    }
          {if (true) return vector;}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseBoolean() throws ParseException, EPMCException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
                  {if (true) return ExpressionLiteral.getTrue(contextVal);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                  {if (true) return ExpressionLiteral.getFalse(contextVal);}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3_1() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) return true;
    }
    return false;
  }

  /** Generated Token Manager. */
  public GuardedCommandExpressionParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x78032080,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x78032080,0x78032080,0x78010080,0x78030080,0x0,0x30000000,0x10080,0x48000000,0x100000,0x0,0x2000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x80000000,0x40000000,0x410482,0x0,0x0,0x0,0x0,0x18000,0x60000,0x60000,0x410482,0x400482,0x82,0x82,0x20000000,0x0,0x0,0x2,0x0,0x20000000,0x400,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x8,0x2,0x4,0x0,0x0,0x1c0801,0x60,0x60,0x780,0x780,0x0,0x0,0x0,0x1c0800,0x1c0800,0x0,0x0,0x0,0x0,0x0,0x0,0x40000,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GuardedCommandExpressionParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GuardedCommandExpressionParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GuardedCommandExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GuardedCommandExpressionParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GuardedCommandExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GuardedCommandExpressionParser(GuardedCommandExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GuardedCommandExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[87];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 87; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
