package epmc.param.options;

public enum OptionsParam {
    PARAM_OPTIONS,
    PARAM_CATEGORY,
    PARAM_PARAMETER,
    PARAM_CANCELLATOR,
    PARAM_ELIMINATION_ORDER,
    PARAM_ELIMINATION_SELF_LOOP_METHOD,
    PARAM_FUNCTION_TYPE,
    
    PARAM_FRACTION_EXPORTER,
    
    PARAM_DAG_EXPORTER,
    PARAM_DAG_USE_PROB_SIMPLIFIER,
    PARAM_DAG_NODE_STORE,
    PARAM_DAG_NODE_LOOKUP,
    PARAM_DAG_PROB_SIMPLIFIER_NUMBER_TYPE,
    PARAM_DAG_PROB_SIMPLIFIER_BITS,
    PARAM_DAG_PROB_SIMPLIFIER_DOUBLE_CUTOFF_BIN_DIGITS,
    PARAM_DAG_PROB_SIMPLIFIER_DOUBLE_PROB_STORAGE,
    PARAM_DAG_PROB_SIMPLIFIER_DOUBLE_PROB_LOOKUP,
    
    PARAM_STATISTICS_SEND,
    PARAM_FUNCTION_LOADER,
    PARAM_FUNCTION_INPUT_FILENAME,
    
    PARAM_POINTS,
    PARAM_POINTS_TYPE,
    PARAM_POINTS_EVALUATORS,
    PARAM_POINTS_EXPORTER,
    PARAM_POINTS_EVALUATOR_RESULT_TYPE,
    PARAM_POINTS_EXPORTER_POINT_FORMAT,
    PARAM_POINTS_EXPORTER_POINT_INTERVAL_FORMAT,
    PARAM_POINTS_EXPORTER_RESULT_FORMAT,
    PARAM_POINTS_EXPORTER_RESULT_INTERVAL_FORMAT,
    PARAM_POINTS_EXPORTER_POINT_FORCE_INTERVAL,
    PARAM_POINTS_EXPORTER_RESULT_FORCE_INTERVAL,
}
