package epmc.dd.buddy;

public enum OptionsDDBuDDy {
    OPTIONS_DD_BUDDY,
    DD_BUDDY_CATEGORY,
    DD_BUDDY_INIT_CACHE_SIZE,
    DD_BUDDY_INIT_NODES,
    DD_BUDDY_CACHE_RATIO,
    DD_BUDDY_MAX_INCREASE,
    DD_BUDDY_MAX_NODE_NUM,
    DD_BUDDY_MIN_FREE_NODES,
    DD_BUDDY_INIT_VARNUM,
}
